version: '3'
services:
  node-app:
    build: .
    container_name: node-app
    ports:
      - 5000:5000
    environment:
      - PORT=${PORT}
      - APP_NAME=${APP_NAME}
      - JWT_SECRET=${JWT_SECRET}
      - MONGO_URI=${MONGO_URI}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - NODE_ENV=${NODE_ENV}
      - BASE_URL=${BASE_URL}

  redis:
    image: redis/redis-stack-server:latest
    container_name: redis-stack-server
    ports:
      - 6379:6379