version: '3'
services:
  node-app:
    build: .
    container_name: node-app
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - 5000:5000
    environment:
      - PORT=${PORT}
      - APP_NAME=${APP_NAME}
      - JWT_SECRET=${JWT_SECRET}
      - MONGO_URI=${MONGO_URI}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - NODE_ENV=${NODE_ENV}
      - BASE_URL=${BASE_URL}
    command: npm run dev

  redis:
    image: redis/redis-stack:latest
    container_name: redis-stack
    ports:
      - 6379:6379