version: '3'
services:
  node-app:
    build:
      context: .
      args:
        - NODE_ENV=${NODE_ENV}
    container_name: node-app
    ports:
      - 5000:5000
    environment:
      - PORT=${PORT}
      - APP_NAME=${APP_NAME}
      - JWT_SECRET=${JWT_SECRET}
      - MONGO_URI=${MONGO_URI}
      - REDIS_HOST=redis
      - REDIS_PORT=6379

      