version: '3'
services:
  node-app:
    build: .
    environment:
      - NODE_ENV=${NODE_ENV}
      - BASE_URL=${BASE_URL}

  redis:
    image: redis/redis-stack-server:latest
    container_name: redis-stack-server