const teams = [
	{
		name: "Arsenal",
		stadium: "Emirates Stadium",
		location: "London, England",
		manager: "Mikel Arteta",
		nickname: "The Gunners",
	},
	{
		name: "Aston Villa",
		stadium: "Villa Park",
		location: "Birmingham, England",
		manager: "Dean Smith",
		nickname: "The Villans",
	},
	{
		name: "Brentford",
		stadium: "Brentford Community Stadium",
		location: "Brentford, London, England",
		manager: "Thomas Frank",
		nickname: "The Bees",
	},
	{
		name: "Brighton & Hove Albion",
		stadium: "Amex Stadium",
		location: "Brighton & Hove, England",
		manager: "Graham Potter",
		nickname: "The Seagulls",
	},
	{
		name: "Burnley",
		stadium: "Turf Moor",
		location: "Burnley, England",
		manager: "Sean Dyche",
		nickname: "The Clarets",
	},
	{
		name: "Chelsea",
		stadium: "Stamford Bridge",
		location: "London, England",
		manager: "Thomas Tuchel",
		nickname: "The Blues",
	},
	{
		name: "Crystal Palace",
		stadium: "Selhurst Park",
		location: "London, England",
		manager: "Patrick Vieira",
		nickname: "The Eagles",
	},
	{
		name: "Everton",
		stadium: "Goodison Park",
		location: "Liverpool, England",
		manager: "Rafael Benitez",
		nickname: "The Toffees",
	},
	{
		name: "Leeds United",
		stadium: "Elland Road",
		location: "Leeds, England",
		manager: "Marcelo Bielsa",
		nickname: "The Whites",
	},
	{
		name: "Leicester City",
		stadium: "King Power Stadium",
		location: "Leicester, England",
		manager: "Brendan Rodgers",
		nickname: "The Foxes",
	},
	{
		name: "Liverpool",
		stadium: "Anfield",
		location: "Liverpool, England",
		manager: "Jurgen Klopp",
		nickname: "The Reds",
	},
	{
		name: "Manchester City",
		stadium: "Etihad Stadium",
		location: "Manchester, England",
		manager: "Pep Guardiola",
		nickname: "The Citizens",
	},
	{
		name: "Manchester United",
		stadium: "Old Trafford",
		location: "Manchester, England",
		manager: "Ole Gunnar Solskjaer",
		nickname: "The Red Devils",
	},
	{
		name: "Newcastle United",
		stadium: "St James' Park",
		location: "Newcastle upon Tyne, England",
		manager: "Eddie Howe",
		nickname: "The Magpies",
	},
	{
		name: "Norwich City",
		stadium: "Carrow Road",
		location: "Norwich, England",
		manager: "Daniel Farke",
		nickname: "The Canaries",
	},
	{
		name: "Southampton",
		stadium: "St Mary's Stadium",
		location: "Southampton, England",
		manager: "Ralph Hasenhuttl",
		nickname: "The Saints",
	},
	{
		name: "Tottenham Hotspur",
		stadium: "Tottenham Hotspur Stadium",
		location: "London, England",
		manager: "Nuno Espirito Santo",
		nickname: "Spurs",
	},
	{
		name: "Watford",
		stadium: "Vicarage Road",
		location: "Watford, England",
		manager: "Xisco Munoz",
		nickname: "The Hornets",
	},
	{
		name: "West Ham United",
		stadium: "London Stadium",
		location: "London, England",
		manager: "David Moyes",
		nickname: "The Hammers",
	},
	{
		name: "Wolverhampton Wanderers",
		stadium: "Molineux Stadium",
		location: "Wolverhampton, England",
		manager: "Bruno Lage",
		nickname: "Wolves",
	},
];

export default teams;
